// resources/js/Components/Dashboard/ActivityTable.vue
<script setup>
defineProps({
    title: {
        type: String,
        required: true,
    },
    subtitle: {
        type: String,
        default: '',
    },
    columns: {
        type: Array,
        default: () => [],
    },
    rows: {
        type: Array,
        default: () => [],
    },
});
</script>

<template>
    <div class="table-wrap">
        <div class="card-header">
            <div>
                <p class="card-title">{{ title }}</p>
                <p v-if="subtitle" class="card-subtitle">{{ subtitle }}</p>
            </div>
        </div>

        <table class="table-standard">
            <thead>
                <tr>
                    <th v-for="column in columns" :key="column.key">
                        {{ column.label }}
                    </th>
                </tr>
            </thead>

            <tbody>
                <tr v-for="(row, index) in rows" :key="row.id || index">
                    <td v-for="column in columns" :key="column.key">
                        <slot :name="column.key" :row="row">
                            {{ row[column.key] }}
                        </slot>
                    </td>
                </tr>

                <tr v-if="rows.length === 0">
                    <td :colspan="columns.length" class="table-empty">
                        No records found.
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
</template>

// resources/js/Components/Dashboard/ActivityTable.jsx
import React from 'react';

export default function ActivityTable({ title, subtitle = '', columns = [], rows = [] }) {
    const renderStatus = (status) => {
        const lower = String(status || '').toLowerCase();
        let indicatorClass = 'status-pending';
        if (['confirmed', 'assigned', 'in_progress'].includes(lower)) {
            indicatorClass = 'status-info';
        } else if (lower === 'completed') {
            indicatorClass = 'status-active';
        } else if (['cancelled', 'refunded'].includes(lower)) {
            indicatorClass = 'status-danger';
        }

        return (
            <span className={`status-indicator ${indicatorClass}`}>
                {status}
            </span>
        );
    };

    return (
        <div className="table-wrap">
            <div className="card-header">
                <div>
                    <p className="card-title">{title}</p>
                    {subtitle && <p className="card-subtitle">{subtitle}</p>}
                </div>
            </div>

            <table className="table-standard">
                <thead>
                    <tr>
                        {columns.map((column) => (
                            <th key={column.key}>
                                {column.label}
                            </th>
                        ))}
                    </tr>
                </thead>

                <tbody>
                    {rows.map((row, index) => (
                        <tr key={row.id || index}>
                            {columns.map((column) => (
                                <td key={column.key}>
                                    {column.render 
                                        ? column.render(row) 
                                        : column.key === 'status' 
                                            ? renderStatus(row[column.key]) 
                                            : row[column.key]}
                                </td>
                            ))}
                        </tr>
                    ))}

                    {rows.length === 0 && (
                        <tr>
                            <td colSpan={columns.length} className="table-empty">
                                No records found.
                            </td>
                        </tr>
                    )}
                </tbody>
            </table>
        </div>
    );
}
