// resources/js/Pages/Caregiver/Visits/Show.jsx
import React from 'react';
import { Head, Link } from '@inertiajs/react';
import CaregiverLayout from '../../../Layouts/CaregiverLayout';

export default function Show({ booking }) {
    const formatDate = (dateString) => {
        if (!dateString) return '—';
        return new Date(dateString).toLocaleDateString('en-US', {
            weekday: 'long', month: 'long', day: 'numeric',
            hour: '2-digit', minute: '2-digit'
        });
    };

    return (
        <>
            <Head title={`Visit Details: ${booking.client?.user?.first_name}`} />
            
            <div className="space-y-6">
                <div className="flex items-center gap-4">
                    <Link href="/caregiver/visits" className="text-sm font-medium text-text-muted hover:text-brand-600 transition-colors">
                        &larr; Back to Visits
                    </Link>
                </div>

                <div className="flex flex-col md:flex-row md:justify-between md:items-end gap-4 bg-surface rounded-xl p-6 border border-border shadow-sm">
                    <div>
                        <div className="flex items-center gap-3 mb-2">
                            <span className={`status-indicator ${
                                booking.status === 'in_progress' ? 'status-active' :
                                booking.status === 'completed' ? 'status-success' : 'status-warning'
                            }`}>
                                {booking.status.replace('_', ' ')}
                            </span>
                            <span className="text-sm font-medium text-text-muted">{booking.reference_id || 'Booking'}</span>
                        </div>
                        <h1 className="text-2xl font-bold tracking-tight text-text">
                            Visit with {booking.client?.user?.first_name} {booking.client?.user?.last_name}
                        </h1>
                        <p className="mt-1 text-sm text-text-muted flex items-center">
                            <svg className="w-4 h-4 mr-1 text-brand-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                            {formatDate(booking.scheduled_start_at)}
                        </p>
                    </div>

                    <div className="flex gap-3 mt-4 md:mt-0">
                        {['scheduled', 'confirmed'].includes(booking.status) && (
                            <Link href={`/caregiver/visits/${booking.id}/check-in`} className="btn-primary py-2 px-6 flex items-center gap-2">
                                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1"></path></svg>
                                Start Visit (Check In)
                            </Link>
                        )}
                        {booking.status === 'in_progress' && (
                            <Link href={`/caregiver/visits/${booking.id}/active`} className="btn-primary py-2 px-6 bg-amber-500 hover:bg-amber-600 border-amber-600 flex items-center gap-2">
                                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z"></path><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                                Active Visit Dashboard
                            </Link>
                        )}
                        {booking.status === 'completed' && booking.visitReport && booking.visitReport.status !== 'submitted' && (
                            <Link href={`/caregiver/visits/reports/${booking.visitReport.id}`} className="btn-primary py-2 px-6">
                                Submit Final Report
                            </Link>
                        )}
                        {booking.status === 'completed' && booking.visitReport && booking.visitReport.status === 'submitted' && (
                            <Link href={`/caregiver/visits/reports/${booking.visitReport.id}`} className="btn-secondary py-2 px-6">
                                View Submitted Report
                            </Link>
                        )}
                    </div>
                </div>

                <div className="grid gap-6 md:grid-cols-3">
                    <div className="md:col-span-2 space-y-6">
                        <div className="card p-6">
                            <h2 className="text-lg font-bold text-text mb-4 border-b border-border pb-2">Service Details</h2>
                            <div className="space-y-4">
                                <div>
                                    <h3 className="text-sm font-medium text-text-muted">Requested Service</h3>
                                    <p className="text-text font-medium mt-1">{booking.service?.name}</p>
                                    <p className="text-sm text-text-muted mt-1">{booking.service?.description}</p>
                                </div>
                                {booking.special_instructions && (
                                    <div className="bg-amber-50 rounded-lg p-4 border border-amber-100">
                                        <h3 className="text-sm font-bold text-amber-800 flex items-center gap-2">
                                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z"></path></svg>
                                            Special Instructions
                                        </h3>
                                        <p className="text-amber-900 mt-2 text-sm">{booking.special_instructions}</p>
                                    </div>
                                )}
                            </div>
                        </div>

                        <div className="card p-6">
                            <h2 className="text-lg font-bold text-text mb-4 border-b border-border pb-2">Client Information</h2>
                            <div className="grid md:grid-cols-2 gap-4">
                                <div>
                                    <h3 className="text-sm font-medium text-text-muted">Full Name</h3>
                                    <p className="text-text font-medium mt-1">{booking.client?.user?.first_name} {booking.client?.user?.last_name}</p>
                                </div>
                                <div>
                                    <h3 className="text-sm font-medium text-text-muted">Phone Number</h3>
                                    <p className="text-text font-medium mt-1">{booking.client?.user?.phone || 'Not provided'}</p>
                                </div>
                                <div className="md:col-span-2">
                                    <h3 className="text-sm font-medium text-text-muted">Address</h3>
                                    <p className="text-text font-medium mt-1">
                                        {booking.client?.address}
                                        {booking.client?.city && `, ${booking.client.city}`}
                                    </p>
                                </div>
                                {booking.client?.medical_conditions && (
                                    <div className="md:col-span-2 mt-2">
                                        <h3 className="text-sm font-medium text-text-muted mb-2">Known Medical Conditions</h3>
                                        <div className="flex flex-wrap gap-2">
                                            {Array.isArray(booking.client.medical_conditions) 
                                                ? booking.client.medical_conditions.map((condition, i) => (
                                                    <span key={i} className="px-3 py-1 bg-rose-50 text-rose-700 rounded-full text-xs font-bold border border-rose-100">
                                                        {condition}
                                                    </span>
                                                  ))
                                                : <span className="text-sm text-text">{booking.client.medical_conditions}</span>
                                            }
                                        </div>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>

                    <div className="space-y-6">
                        <div className="card p-6">
                            <h2 className="text-lg font-bold text-text mb-4 border-b border-border pb-2">Visit Timeline</h2>
                            <div className="relative border-l-2 border-brand-200 ml-3 space-y-6">
                                <div className="relative pl-6">
                                    <div className={`absolute -left-[9px] top-1 w-4 h-4 rounded-full border-2 border-surface ${
                                        ['confirmed', 'in_progress', 'completed'].includes(booking.status) ? 'bg-brand-500' : 'bg-border'
                                    }`}></div>
                                    <h3 className="text-sm font-bold text-text">Scheduled</h3>
                                    <p className="text-xs text-text-muted mt-1">{formatDate(booking.scheduled_start_at)}</p>
                                </div>
                                
                                <div className="relative pl-6">
                                    <div className={`absolute -left-[9px] top-1 w-4 h-4 rounded-full border-2 border-surface ${
                                        ['in_progress', 'completed'].includes(booking.status) ? 'bg-brand-500' : 'bg-border'
                                    }`}></div>
                                    <h3 className="text-sm font-bold text-text">Check-in</h3>
                                    <p className="text-xs text-text-muted mt-1">
                                        {booking.visitReport?.arrival_time ? formatDate(booking.visitReport.arrival_time) : 'Waiting for check-in'}
                                    </p>
                                </div>
                                
                                <div className="relative pl-6">
                                    <div className={`absolute -left-[9px] top-1 w-4 h-4 rounded-full border-2 border-surface ${
                                        booking.status === 'completed' ? 'bg-brand-500' : 'bg-border'
                                    }`}></div>
                                    <h3 className="text-sm font-bold text-text">Check-out</h3>
                                    <p className="text-xs text-text-muted mt-1">
                                        {booking.visitReport?.departure_time ? formatDate(booking.visitReport.departure_time) : 'Pending'}
                                    </p>
                                </div>

                                <div className="relative pl-6">
                                    <div className={`absolute -left-[9px] top-1 w-4 h-4 rounded-full border-2 border-surface ${
                                        booking.visitReport?.status === 'submitted' ? 'bg-emerald-500' : 'bg-border'
                                    }`}></div>
                                    <h3 className="text-sm font-bold text-text">Report Submitted</h3>
                                    <p className="text-xs text-text-muted mt-1">
                                        {booking.visitReport?.submitted_at ? formatDate(booking.visitReport.submitted_at) : 'Pending'}
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}

Show.layout = page => <CaregiverLayout title="Visit Details" description="Prepare for your upcoming visit">{page}</CaregiverLayout>;

// resources/js/Pages/Caregiver/Visits/Show.vue
<script setup>
import { Head, Link } from '@inertiajs/vue3';
import CaregiverLayout from '../../../Layouts/CaregiverLayout.vue';
import VisitStatusBadge from '../../../Components/Visits/VisitStatusBadge.vue';
import VisitTimeline from '../../../Components/Visits/VisitTimeline.vue';

defineOptions({ layout: CaregiverLayout });

const props = defineProps({
    booking: { type: Object, required: true },
});

const formatDateTime = (dt) => {
    if (!dt) return '—';
    return new Date(dt).toLocaleString('en-GB', {
        weekday: 'long', day: 'numeric', month: 'long', hour: '2-digit', minute: '2-digit',
    });
};

const canCheckIn = (b) =>
    (b.status === 'confirmed' || b.status === 'scheduled') && !b.visit_report?.arrival_time;

const isActive = (b) =>
    b.status === 'in_progress' && b.visit_report?.arrival_time && !b.visit_report?.departure_time;
</script>

<template>
    <Head :title="`Visit – ${booking.client?.user?.name ?? 'Client'}`" />

    <div class="space-y-6">
        <!-- Back -->
        <Link href="/caregiver/visits" class="inline-flex items-center gap-2 text-sm text-text-muted hover:text-text transition">
            <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
            Back to Visits
        </Link>

        <!-- Header -->
        <div class="flex items-start justify-between gap-4">
            <div>
                <h1 class="text-2xl font-bold text-text">{{ booking.client?.user?.name ?? 'Client Visit' }}</h1>
                <p class="mt-1 text-text-muted">{{ booking.service_name_snapshot ?? booking.service?.name ?? 'Care Service' }}</p>
            </div>
            <VisitStatusBadge :status="booking.visit_report?.status ?? booking.status" size="lg" />
        </div>

        <div class="grid gap-6 lg:grid-cols-[1fr_340px]">
            <!-- Main content -->
            <div class="space-y-5">
                <!-- Client Information -->
                <div class="rounded-2xl border border-border bg-surface p-5 shadow-sm">
                    <h2 class="mb-4 text-sm font-semibold text-text-soft uppercase tracking-wide">Client Information</h2>
                    <div class="grid gap-3 sm:grid-cols-2">
                        <div>
                            <p class="text-xs text-text-soft">Full Name</p>
                            <p class="font-medium text-text">{{ booking.client?.user?.name ?? '—' }}</p>
                        </div>
                        <div>
                            <p class="text-xs text-text-soft">Phone</p>
                            <p class="font-medium text-text">{{ booking.client?.user?.phone ?? '—' }}</p>
                        </div>
                        <div class="sm:col-span-2">
                            <p class="text-xs text-text-soft">Address</p>
                            <p class="font-medium text-text">{{ booking.client?.address ?? '—' }}</p>
                        </div>
                    </div>
                </div>

                <!-- Service Information -->
                <div class="rounded-2xl border border-border bg-surface p-5 shadow-sm">
                    <h2 class="mb-4 text-sm font-semibold text-text-soft uppercase tracking-wide">Service Information</h2>
                    <div class="grid gap-3 sm:grid-cols-2">
                        <div>
                            <p class="text-xs text-text-soft">Service Type</p>
                            <p class="font-medium text-text">{{ booking.service_name_snapshot ?? booking.service?.name }}</p>
                        </div>
                        <div>
                            <p class="text-xs text-text-soft">Duration</p>
                            <p class="font-medium text-text">{{ booking.service_duration_snapshot ?? '—' }} mins</p>
                        </div>
                        <div>
                            <p class="text-xs text-text-soft">Scheduled Start</p>
                            <p class="font-medium text-text">{{ formatDateTime(booking.scheduled_start_at) }}</p>
                        </div>
                        <div>
                            <p class="text-xs text-text-soft">Scheduled End</p>
                            <p class="font-medium text-text">{{ formatDateTime(booking.scheduled_end_at) }}</p>
                        </div>
                    </div>
                </div>

                <!-- Care Instructions -->
                <div v-if="booking.care_instructions" class="rounded-2xl border border-amber-200 bg-amber-50 p-5">
                    <h2 class="mb-3 flex items-center gap-2 text-sm font-semibold text-amber-800">
                        <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                        </svg>
                        Care Instructions
                    </h2>
                    <p class="text-sm leading-relaxed text-amber-900">{{ booking.care_instructions }}</p>
                </div>
            </div>

            <!-- Sidebar -->
            <div class="space-y-5">
                <!-- Timeline -->
                <VisitTimeline
                    :check-in-time="booking.visit_report?.arrival_time"
                    :check-out-time="booking.visit_report?.departure_time"
                />

                <!-- Action Button -->
                <div class="rounded-2xl border border-border bg-surface p-5 shadow-sm">
                    <h2 class="mb-3 text-sm font-semibold text-text-soft uppercase tracking-wide">Actions</h2>

                    <Link
                        v-if="canCheckIn(booking)"
                        :href="`/caregiver/visits/${booking.id}/check-in`"
                        class="btn-primary w-full justify-center text-center"
                    >
                        <svg class="mr-2 h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                        </svg>
                        GPS Check-In
                    </Link>

                    <Link
                        v-else-if="isActive(booking)"
                        :href="`/caregiver/visits/${booking.id}/active`"
                        class="w-full justify-center rounded-xl bg-amber-500 px-4 py-2.5 text-center text-sm font-medium text-white hover:bg-amber-600 transition block"
                    >
                        View Active Visit
                    </Link>

                    <p v-else class="text-sm text-text-muted">No actions available for this visit.</p>
                </div>
            </div>
        </div>
    </div>
</template>
