// resources/js/Pages/Family/Visits/Show.jsx
import React from 'react';
import { Head, Link } from '@inertiajs/react';
import FamilyLayout from '../../../Layouts/FamilyLayout';

export default function Show({ report }) {
    if (!report) {
        return (
            <div className="alert-danger">
                <span className="font-semibold">Error:</span> Visit report not found.
            </div>
        );
    }

    const formatDate = (dateString) => {
        if (!dateString) return '—';
        return new Date(dateString).toLocaleDateString('en-US', {
            weekday: 'long', month: 'long', day: 'numeric', year: 'numeric'
        });
    };

    const formatTime = (dateString) => {
        if (!dateString) return '—';
        return new Date(dateString).toLocaleTimeString('en-US', {
            hour: '2-digit', minute: '2-digit'
        });
    };

    const formatDuration = (arrival, departure) => {
        if (!arrival || !departure) return '—';
        const start = new Date(arrival);
        const end = new Date(departure);
        const diffMs = end - start;
        const diffMins = Math.round(diffMs / 60000);
        if (diffMins < 60) return `${diffMins} mins`;
        const hrs = Math.floor(diffMins / 60);
        const mins = diffMins % 60;
        return `${hrs}h ${mins}m`;
    };

    return (
        <>
            <Head title={`Visit Report - ${formatDate(report.arrival_time)}`} />

            <div className="space-y-6 max-w-4xl mx-auto">
                <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                    <div>
                        <div className="flex items-center gap-2 mb-2">
                            <Link href="/family/reports" className="text-sm font-medium text-brand-600 hover:text-brand-800 flex items-center gap-1">
                                <svg className="h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 19l-7-7m0 0l7-7m-7 7h18" /></svg>
                                Back to Reports
                            </Link>
                        </div>
                        <h1 className="text-2xl font-bold tracking-tight text-text">Visit Report</h1>
                        <p className="mt-1 text-sm text-text-muted">
                            Detailed care report for {formatDate(report.arrival_time || report.created_at)}
                        </p>
                    </div>
                    <div className="flex items-center gap-3">
                        <button className="btn-secondary btn-sm" onClick={() => window.print()}>
                            <svg className="h-4 w-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z" /></svg>
                            Download PDF
                        </button>
                    </div>
                </div>

                <div className="grid gap-6 md:grid-cols-3">
                    <div className="md:col-span-2 space-y-6">
                        <div className="card">
                            <div className="card-header border-b border-border">
                                <h2 className="text-lg font-semibold text-text">Care Summary</h2>
                            </div>
                            <div className="p-6 space-y-6">
                                <div>
                                    <h3 className="text-sm font-medium text-text-soft mb-2">Client Condition</h3>
                                    <p className="text-text bg-surface-muted p-4 rounded-lg">{report.client_condition || 'No condition notes provided.'}</p>
                                </div>
                                <div>
                                    <h3 className="text-sm font-medium text-text-soft mb-2">Caregiver Notes</h3>
                                    <p className="text-text bg-surface-muted p-4 rounded-lg">{report.caregiver_notes || 'No general notes provided.'}</p>
                                </div>
                                {report.services_performed && (
                                    <div>
                                        <h3 className="text-sm font-medium text-text-soft mb-2">Services Performed</h3>
                                        <ul className="list-disc list-inside space-y-1 text-text ml-1">
                                            {Array.isArray(report.services_performed) ? report.services_performed.map((srv, idx) => (
                                                <li key={idx}>{srv}</li>
                                            )) : <li>{report.services_performed}</li>}
                                        </ul>
                                    </div>
                                )}
                            </div>
                        </div>
                    </div>

                    <div className="space-y-6">
                        <div className="card">
                            <div className="card-header border-b border-border">
                                <h2 className="text-lg font-semibold text-text">Visit Details</h2>
                            </div>
                            <div className="p-6 space-y-4">
                                <div>
                                    <p className="text-xs font-semibold text-text-soft uppercase tracking-wide">Caregiver</p>
                                    <p className="mt-1 font-medium text-text">{report.caregiver?.user?.name || 'Unknown Caregiver'}</p>
                                </div>
                                <div className="border-t border-border pt-4">
                                    <p className="text-xs font-semibold text-text-soft uppercase tracking-wide">Status</p>
                                    <div className="mt-1">
                                        <span className={`status-indicator ${report.departure_time ? 'status-active' : 'status-info'}`}>
                                            {report.departure_time ? 'Completed' : 'In Progress'}
                                        </span>
                                    </div>
                                </div>
                                <div className="border-t border-border pt-4 grid grid-cols-2 gap-4">
                                    <div>
                                        <p className="text-xs font-semibold text-text-soft uppercase tracking-wide">Arrival Time</p>
                                        <p className="mt-1 font-medium text-text">{formatTime(report.arrival_time)}</p>
                                    </div>
                                    <div>
                                        <p className="text-xs font-semibold text-text-soft uppercase tracking-wide">Departure Time</p>
                                        <p className="mt-1 font-medium text-text">{formatTime(report.departure_time)}</p>
                                    </div>
                                </div>
                                <div className="border-t border-border pt-4">
                                    <p className="text-xs font-semibold text-text-soft uppercase tracking-wide">Total Duration</p>
                                    <p className="mt-1 font-medium text-text">{formatDuration(report.arrival_time, report.departure_time)}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}

Show.layout = page => <FamilyLayout>{page}</FamilyLayout>;

// resources/js/Pages/Caregiver/Visits/Show.vue
<script setup>
import { Head, Link } from '@inertiajs/vue3';
import CaregiverLayout from '../../../Layouts/CaregiverLayout.vue';
import VisitStatusBadge from '../../../Components/Visits/VisitStatusBadge.vue';
import VisitTimeline from '../../../Components/Visits/VisitTimeline.vue';

defineOptions({ layout: CaregiverLayout });

const props = defineProps({
    booking: { type: Object, required: true },
});

const formatDateTime = (dt) => {
    if (!dt) return '—';
    return new Date(dt).toLocaleString('en-GB', {
        weekday: 'long', day: 'numeric', month: 'long', hour: '2-digit', minute: '2-digit',
    });
};

const canCheckIn = (b) =>
    (b.status === 'confirmed' || b.status === 'scheduled') && !b.visit_report?.arrival_time;

const isActive = (b) =>
    b.status === 'in_progress' && b.visit_report?.arrival_time && !b.visit_report?.departure_time;
</script>

<template>
    <Head :title="`Visit – ${booking.client?.user?.name ?? 'Client'}`" />

    <div class="space-y-6">
        <!-- Back -->
        <Link href="/caregiver/visits" class="inline-flex items-center gap-2 text-sm text-text-muted hover:text-text transition">
            <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
            </svg>
            Back to Visits
        </Link>

        <!-- Header -->
        <div class="flex items-start justify-between gap-4">
            <div>
                <h1 class="text-2xl font-bold text-text">{{ booking.client?.user?.name ?? 'Client Visit' }}</h1>
                <p class="mt-1 text-text-muted">{{ booking.service_name_snapshot ?? booking.service?.name ?? 'Care Service' }}</p>
            </div>
            <VisitStatusBadge :status="booking.visit_report?.status ?? booking.status" size="lg" />
        </div>

        <div class="grid gap-6 lg:grid-cols-[1fr_340px]">
            <!-- Main content -->
            <div class="space-y-5">
                <!-- Client Information -->
                <div class="rounded-2xl border border-border bg-surface p-5 shadow-sm">
                    <h2 class="mb-4 text-sm font-semibold text-text-soft uppercase tracking-wide">Client Information</h2>
                    <div class="grid gap-3 sm:grid-cols-2">
                        <div>
                            <p class="text-xs text-text-soft">Full Name</p>
                            <p class="font-medium text-text">{{ booking.client?.user?.name ?? '—' }}</p>
                        </div>
                        <div>
                            <p class="text-xs text-text-soft">Phone</p>
                            <p class="font-medium text-text">{{ booking.client?.user?.phone ?? '—' }}</p>
                        </div>
                        <div class="sm:col-span-2">
                            <p class="text-xs text-text-soft">Address</p>
                            <p class="font-medium text-text">{{ booking.client?.address ?? '—' }}</p>
                        </div>
                    </div>
                </div>

                <!-- Service Information -->
                <div class="rounded-2xl border border-border bg-surface p-5 shadow-sm">
                    <h2 class="mb-4 text-sm font-semibold text-text-soft uppercase tracking-wide">Service Information</h2>
                    <div class="grid gap-3 sm:grid-cols-2">
                        <div>
                            <p class="text-xs text-text-soft">Service Type</p>
                            <p class="font-medium text-text">{{ booking.service_name_snapshot ?? booking.service?.name }}</p>
                        </div>
                        <div>
                            <p class="text-xs text-text-soft">Duration</p>
                            <p class="font-medium text-text">{{ booking.service_duration_snapshot ?? '—' }} mins</p>
                        </div>
                        <div>
                            <p class="text-xs text-text-soft">Scheduled Start</p>
                            <p class="font-medium text-text">{{ formatDateTime(booking.scheduled_start_at) }}</p>
                        </div>
                        <div>
                            <p class="text-xs text-text-soft">Scheduled End</p>
                            <p class="font-medium text-text">{{ formatDateTime(booking.scheduled_end_at) }}</p>
                        </div>
                    </div>
                </div>

                <!-- Care Instructions -->
                <div v-if="booking.care_instructions" class="rounded-2xl border border-amber-200 bg-amber-50 p-5">
                    <h2 class="mb-3 flex items-center gap-2 text-sm font-semibold text-amber-800">
                        <svg class="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z" />
                        </svg>
                        Care Instructions
                    </h2>
                    <p class="text-sm leading-relaxed text-amber-900">{{ booking.care_instructions }}</p>
                </div>
            </div>

            <!-- Sidebar -->
            <div class="space-y-5">
                <!-- Timeline -->
                <VisitTimeline
                    :check-in-time="booking.visit_report?.arrival_time"
                    :check-out-time="booking.visit_report?.departure_time"
                />

                <!-- Action Button -->
                <div class="rounded-2xl border border-border bg-surface p-5 shadow-sm">
                    <h2 class="mb-3 text-sm font-semibold text-text-soft uppercase tracking-wide">Actions</h2>

                    <Link
                        v-if="canCheckIn(booking)"
                        :href="`/caregiver/visits/${booking.id}/check-in`"
                        class="btn-primary w-full justify-center text-center"
                    >
                        <svg class="mr-2 h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                        </svg>
                        GPS Check-In
                    </Link>

                    <Link
                        v-else-if="isActive(booking)"
                        :href="`/caregiver/visits/${booking.id}/active`"
                        class="w-full justify-center rounded-xl bg-amber-500 px-4 py-2.5 text-center text-sm font-medium text-white hover:bg-amber-600 transition block"
                    >
                        View Active Visit
                    </Link>

                    <p v-else class="text-sm text-text-muted">No actions available for this visit.</p>
                </div>
            </div>
        </div>
    </div>
</template>
