// resources/js/Components/Layout/AppSidebar.vue
<script setup>
import { computed } from 'vue';
import { Link, usePage } from '@inertiajs/vue3';
import AppLogo from './AppLogo.vue';

const props = defineProps({
    navigation: {
        type: Array,
        default: () => [],
    },
    roleLabel: {
        type: String,
        default: 'Workspace',
    },
});

const page = usePage();

const currentUrl = computed(() => page.url || '');

const isActive = (item) => {
    if (!item?.href) {
        return false;
    }

    return currentUrl.value === item.href || currentUrl.value.startsWith(`${item.href}/`);
};
</script>

<template>
    <aside class="hidden h-screen w-72 shrink-0 border-r border-border bg-surface xl:flex xl:flex-col">
        <div class="border-b border-border px-6 py-5">
            <AppLogo />
        </div>

        <div class="border-b border-border px-6 py-4">
            <p class="text-xs font-semibold uppercase tracking-[0.14em] text-text-soft">Active workspace</p>
            <p class="mt-2 text-sm font-semibold text-text">{{ roleLabel }}</p>
        </div>

        <nav class="flex-1 space-y-1 overflow-y-auto px-4 py-5">
            <Link
                v-for="item in navigation"
                :key="item.label"
                :href="item.href || '#'"
                class="panel-nav-link"
                :class="{ 'panel-nav-link-active': isActive(item) }"
            >
                <span
                    class="flex h-9 w-9 items-center justify-center rounded-xl"
                    :class="isActive(item) ? 'bg-brand-600 text-white' : 'bg-secondary-50 text-text-soft'"
                    aria-hidden="true"
                >
                    <component :is="item.icon" class="h-5 w-5" />
                </span>
                <span class="flex-1">{{ item.label }}</span>
                <span
                    v-if="item.badge"
                    class="badge"
                    :class="isActive(item) ? 'badge-primary' : 'badge-secondary'"
                >
                    {{ item.badge }}
                </span>
            </Link>
        </nav>
    </aside>
</template>

// resources/js/Components/Layout/AppSidebar.jsx
import React from 'react';
import { Link, usePage } from '@inertiajs/react';
import AppLogo from './AppLogo';

export default function AppSidebar({ navigation = [], roleLabel = 'Workspace' }) {
    const { url } = usePage();
    const currentUrl = url || '';

    const isActive = (item) => {
        if (!item?.href) {
            return false;
        }
        return currentUrl === item.href || currentUrl.startsWith(`${item.href}/`);
    };

    return (
        <aside className="hidden h-screen w-72 shrink-0 border-r border-border bg-surface xl:fixed xl:inset-y-0 xl:left-0 xl:z-50 xl:flex xl:flex-col">
            <div className="border-b border-border px-6 py-5">
                <AppLogo />
            </div>

            <div className="border-b border-border px-6 py-4">
                <p className="text-xs font-semibold uppercase tracking-[0.14em] text-text-soft">Active workspace</p>
                <p className="mt-2 text-sm font-semibold text-text">{roleLabel}</p>
            </div>

            <nav className="flex-1 space-y-1 overflow-y-auto px-4 py-5">
                {navigation.map((item) => {
                    const active = isActive(item);
                    const IconComponent = item.icon;
                    return (
                        <Link
                            key={item.label}
                            href={item.href || '#'}
                            className={`panel-nav-link ${active ? 'panel-nav-link-active' : ''}`}
                        >
                            <span
                                className={`flex h-9 w-9 items-center justify-center rounded-xl ${
                                    active ? 'bg-brand-600 text-white' : 'bg-secondary-50 text-text-soft'
                                }`}
                                aria-hidden="true"
                            >
                                {IconComponent && <IconComponent className="h-5 w-5" />}
                            </span>
                            <span className="flex-1">{item.label}</span>
                            {item.badge && (
                                <span className={`badge ${active ? 'badge-primary' : 'badge-secondary'}`}>
                                    {item.badge}
                                </span>
                            )}
                        </Link>
                    );
                })}
            </nav>
        </aside>
    );
}
