// resources/js/Components/Support/LoadingSkeleton.tsx
import React from 'react';

export function LoadingSkeleton() {
    return (
        <div className="animate-pulse space-y-4">
            {[1, 2, 3].map((i) => (
                <div key={i} className="bg-white dark:bg-gray-800 rounded-xl p-5 border border-gray-100 dark:border-gray-700">
                    <div className="flex justify-between items-start mb-4">
                        <div className="flex flex-col gap-2 w-full max-w-md">
                            <div className="flex gap-2">
                                <div className="h-5 w-20 bg-gray-200 dark:bg-gray-700 rounded"></div>
                                <div className="h-5 w-16 bg-gray-200 dark:bg-gray-700 rounded"></div>
                                <div className="h-5 w-16 bg-gray-200 dark:bg-gray-700 rounded"></div>
                            </div>
                            <div className="h-6 w-3/4 bg-gray-200 dark:bg-gray-700 rounded"></div>
                        </div>
                    </div>
                    <div className="space-y-2 mb-4">
                        <div className="h-4 w-full bg-gray-200 dark:bg-gray-700 rounded"></div>
                        <div className="h-4 w-5/6 bg-gray-200 dark:bg-gray-700 rounded"></div>
                    </div>
                    <div className="flex gap-4 pt-4 border-t border-gray-100 dark:border-gray-700">
                        <div className="h-4 w-24 bg-gray-200 dark:bg-gray-700 rounded"></div>
                        <div className="h-4 w-20 bg-gray-200 dark:bg-gray-700 rounded"></div>
                    </div>
                </div>
            ))}
        </div>
    );
}

// resources/js/Components/Messaging/LoadingSkeleton.vue
<template>
    <div class="flex w-full animate-pulse gap-3 p-4">
        <!-- Avatar -->
        <div class="h-12 w-12 shrink-0 rounded-full bg-border/50 dark:bg-border/20"></div>
        <!-- Content -->
        <div class="flex-1 space-y-3 py-1">
            <div class="flex items-center justify-between">
                <div class="h-4 w-1/3 rounded bg-border/50 dark:bg-border/20"></div>
                <div class="h-3 w-10 rounded bg-border/50 dark:bg-border/20"></div>
            </div>
            <div class="h-3 w-3/4 rounded bg-border/50 dark:bg-border/20"></div>
        </div>
    </div>
</template>
