// resources/js/Pages/Caregiver/Visits/Index.vue
<script setup>
import { Head, Link, router } from '@inertiajs/vue3';
import { ref, watch } from 'vue';
import CaregiverLayout from '../../../Layouts/CaregiverLayout.vue';
import LoadingSkeleton from '../../../Components/Visits/LoadingSkeleton.vue';
import VisitCard from '../../../Components/Visits/VisitCard.vue';

defineOptions({ layout: CaregiverLayout });

const props = defineProps({
    bookings: { type: Object, required: true },
    filters: { type: Object, default: () => ({}) },
});

const activeTab = ref(props.filters.tab ?? 'upcoming');
const search = ref(props.filters.search ?? '');
const dateFilter = ref(props.filters.dateFilter ?? '');
const statusFilter = ref(props.filters.statusFilter ?? '');
const loading = ref(false);

const applyFilters = () => {
    loading.value = true;
    router.get('/caregiver/visits', {
        tab: activeTab.value,
        search: search.value,
        date: dateFilter.value,
        status: statusFilter.value,
    }, {
        preserveState: true,
        replace: true,
        onFinish: () => { loading.value = false; },
    });
};

const switchTab = (tab) => {
    activeTab.value = tab;
    statusFilter.value = '';
    applyFilters();
};

let searchTimeout;
watch(search, () => {
    clearTimeout(searchTimeout);
    searchTimeout = setTimeout(applyFilters, 400);
});

const statusOptions = {
    upcoming: [
        { value: '', label: 'All statuses' },
        { value: 'scheduled', label: 'Scheduled' },
        { value: 'confirmed', label: 'Confirmed' },
        { value: 'in_progress', label: 'In Progress' },
    ],
    completed: [
        { value: '', label: 'All' },
        { value: 'completed', label: 'Completed' },
        { value: 'submitted', label: 'Report Submitted' },
        { value: 'reviewed', label: 'Reviewed' },
    ],
};

const tabs = [
    { key: 'upcoming', label: 'Upcoming & Active' },
    { key: 'completed', label: 'Completed' },
];

const formatDate = (d) => {
    if (!d) return '';
    return new Date(d).toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short' });
};
</script>

<template>
    <Head title="My Visits – Caregiver" />

    <div class="space-y-6">
        <!-- Page Header -->
        <div>
            <h1 class="text-2xl font-bold text-text">My Visits</h1>
            <p class="mt-1 text-sm text-text-muted">Manage your scheduled visits, check-ins, check-outs and reports.</p>
        </div>

        <!-- Tabs -->
        <div class="flex gap-1 rounded-xl border border-border bg-surface-subtle p-1">
            <button
                v-for="tab in tabs"
                :key="tab.key"
                type="button"
                class="flex-1 rounded-lg px-4 py-2 text-sm font-medium transition-all duration-200"
                :class="activeTab === tab.key
                    ? 'bg-brand-600 text-white shadow-sm'
                    : 'text-text-muted hover:bg-surface hover:text-text'"
                @click="switchTab(tab.key)"
            >
                {{ tab.label }}
            </button>
        </div>

        <!-- Filters Row -->
        <div class="flex flex-col gap-3 sm:flex-row sm:items-center">
            <!-- Search -->
            <div class="relative flex-1">
                <svg class="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-text-soft" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.8">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
                </svg>
                <input
                    v-model="search"
                    type="search"
                    placeholder="Search by client name or service…"
                    class="w-full rounded-xl border border-border bg-surface-subtle py-2.5 pl-10 pr-4 text-sm text-text placeholder:text-text-soft focus:border-brand-400 focus:outline-none focus:ring-2 focus:ring-brand-100"
                />
            </div>

            <!-- Date filter -->
            <input
                v-model="dateFilter"
                type="date"
                class="rounded-xl border border-border bg-surface-subtle px-4 py-2.5 text-sm text-text focus:border-brand-400 focus:outline-none focus:ring-2 focus:ring-brand-100"
                @change="applyFilters"
            />

            <!-- Status filter -->
            <select
                v-model="statusFilter"
                class="rounded-xl border border-border bg-surface-subtle px-4 py-2.5 text-sm text-text focus:border-brand-400 focus:outline-none focus:ring-2 focus:ring-brand-100"
                @change="applyFilters"
            >
                <option v-for="opt in (statusOptions[activeTab] || statusOptions.upcoming)" :key="opt.value" :value="opt.value">
                    {{ opt.label }}
                </option>
            </select>
        </div>

        <!-- Loading skeletons -->
        <div v-if="loading" class="space-y-4">
            <LoadingSkeleton :rows="3" />
        </div>

        <!-- Visits Grid -->
        <template v-else>
            <div v-if="bookings.data?.length" class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
                <VisitCard
                    v-for="booking in bookings.data"
                    :key="booking.id"
                    :booking="booking"
                />
            </div>

            <!-- Empty State -->
            <div v-else class="flex flex-col items-center justify-center rounded-2xl border border-dashed border-border bg-surface py-16 text-center">
                <div class="mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-brand-50">
                    <svg class="h-8 w-8 text-brand-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.5">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2" />
                    </svg>
                </div>
                <p class="text-base font-semibold text-text">No visits found</p>
                <p class="mt-1 text-sm text-text-muted">
                    {{ activeTab === 'upcoming' ? 'You have no upcoming visits matching your filters.' : 'No completed visits to show.' }}
                </p>
                <button v-if="search || dateFilter || statusFilter" type="button" class="mt-4 btn-secondary btn-sm" @click="search = ''; dateFilter = ''; statusFilter = ''; applyFilters()">
                    Clear Filters
                </button>
            </div>

            <!-- Pagination -->
            <div v-if="bookings.last_page > 1" class="flex items-center justify-between text-sm">
                <span class="text-text-muted">
                    Showing {{ bookings.from }}–{{ bookings.to }} of {{ bookings.total }} visits
                </span>
                <div class="flex gap-1">
                    <Link
                        v-if="bookings.prev_page_url"
                        :href="bookings.prev_page_url"
                        class="btn-secondary btn-sm"
                    >← Prev</Link>
                    <Link
                        v-if="bookings.next_page_url"
                        :href="bookings.next_page_url"
                        class="btn-secondary btn-sm"
                    >Next →</Link>
                </div>
            </div>
        </template>
    </div>
</template>

// resources/js/Pages/Family/Visits/Index.jsx
import React, { useState, useEffect, useMemo } from 'react';
import { Head, Link } from '@inertiajs/react';
import axios from 'axios';
import FamilyLayout from '../../../Layouts/FamilyLayout';

export default function Index() {
    const [visits, setVisits] = useState([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState('');
    const [search, setSearch] = useState('');

    const fetchVisits = async () => {
        setLoading(true);
        setError('');
        try {
            const response = await axios.get('/api/family/visits');
            setVisits(response.data.data || []);
        } catch (e) {
            setError('Failed to load visit reports. Please refresh and try again.');
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchVisits();
    }, []);

    const filtered = useMemo(() => {
        let list = visits;
        if (search.trim()) {
            const q = search.trim().toLowerCase();
            list = list.filter(v => 
                (v.caregiver && v.caregiver.user && v.caregiver.user.name && v.caregiver.user.name.toLowerCase().includes(q)) ||
                (v.client_condition && v.client_condition.toLowerCase().includes(q))
            );
        }
        return list;
    }, [visits, search]);

    const formatDate = (dateString) => {
        if (!dateString) return '—';
        return new Date(dateString).toLocaleDateString('en-US', {
            month: 'short', day: 'numeric', year: 'numeric'
        });
    };

    const formatDuration = (arrival, departure) => {
        if (!arrival || !departure) return '—';
        const start = new Date(arrival);
        const end = new Date(departure);
        const diffMs = end - start;
        const diffMins = Math.round(diffMs / 60000);
        if (diffMins < 60) return `${diffMins} mins`;
        const hrs = Math.floor(diffMins / 60);
        const mins = diffMins % 60;
        return `${hrs}h ${mins}m`;
    };

    return (
        <>
            <Head title="Visit Reports" />

            <div className="space-y-6">
                <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
                    <div>
                        <h1 className="text-2xl font-bold tracking-tight text-text">Completed Visits</h1>
                        <p className="mt-1 text-sm text-text-muted">
                            Review detailed care reports submitted by caregivers.
                        </p>
                    </div>
                </div>

                {error && (
                    <div className="alert-danger">
                        <span className="font-semibold">Error:</span> {error}
                    </div>
                )}

                <div className="flex flex-col gap-3 sm:flex-row sm:items-center">
                    <div className="relative flex-1">
                        <svg className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-text-muted" fill="none" stroke="currentColor" strokeWidth="2" viewBox="0 0 24 24">
                            <circle cx="11" cy="11" r="7" /><path d="M21 21l-4.35-4.35" strokeLinecap="round" />
                        </svg>
                        <input
                            id="visit-search"
                            type="search"
                            placeholder="Search by caregiver or condition..."
                            className="input-field pl-9 block w-full rounded-lg border border-border bg-white px-4 py-2.5 text-sm text-text placeholder:text-text-soft transition duration-200"
                            value={search}
                            onChange={e => setSearch(e.target.value)}
                        />
                    </div>
                </div>

                <div className="table-wrap">
                    <div className="card-header flex items-center justify-between">
                        <div>
                            <p className="card-title">Recent Reports</p>
                            <p className="card-subtitle">{filtered.length} report{filtered.length !== 1 ? 's' : ''} found</p>
                        </div>
                    </div>

                    {loading ? (
                        <div className="divide-y divide-border">
                            {[1, 2, 3, 4].map(n => (
                                <div key={n} className="flex items-center gap-4 p-4">
                                    <div className="h-4 w-48 animate-pulse rounded bg-surface-subtle" />
                                    <div className="h-4 w-24 animate-pulse rounded bg-surface-subtle" />
                                    <div className="h-4 w-16 animate-pulse rounded bg-surface-subtle" />
                                    <div className="ml-auto h-4 w-16 animate-pulse rounded bg-surface-subtle" />
                                </div>
                            ))}
                        </div>
                    ) : (
                        <table className="table-standard">
                            <thead>
                                <tr>
                                    <th>Date</th>
                                    <th>Caregiver</th>
                                    <th>Duration</th>
                                    <th>Status</th>
                                    <th className="text-right">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {filtered.map(visit => (
                                    <tr key={visit.id} className="group hover:bg-surface-subtle transition-colors">
                                        <td className="font-medium text-brand-600">
                                            {formatDate(visit.arrival_time || visit.created_at)}
                                        </td>
                                        <td className="text-text">
                                            {visit.caregiver?.user?.name || 'Unknown Caregiver'}
                                        </td>
                                        <td className="text-text-muted">
                                            {formatDuration(visit.arrival_time, visit.departure_time)}
                                        </td>
                                        <td>
                                            <span className={`status-indicator ${
                                                visit.departure_time ? 'status-active' : 'status-info'
                                            }`}>
                                                {visit.departure_time ? 'Completed' : 'In Progress'}
                                            </span>
                                        </td>
                                        <td className="text-right">
                                            {visit.departure_time ? (
                                                <Link href={`/family/reports/${visit.id}`} className="btn-secondary btn-sm">
                                                    View Report
                                                </Link>
                                            ) : (
                                                <span className="text-xs text-text-soft">Pending report</span>
                                            )}
                                        </td>
                                    </tr>
                                ))}
                                {filtered.length === 0 && (
                                    <tr>
                                        <td colSpan="5" className="table-empty">
                                            <div className="flex flex-col items-center gap-2 py-10">
                                                <svg className="h-10 w-10 text-text-muted opacity-40" fill="none" stroke="currentColor" strokeWidth="1.5" viewBox="0 0 24 24">
                                                    <path d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" strokeLinecap="round" strokeLinejoin="round" />
                                                </svg>
                                                <p className="text-sm text-text-muted">
                                                    {search ? 'No reports match your search.' : 'No completed visit reports yet.'}
                                                </p>
                                            </div>
                                        </td>
                                    </tr>
                                )}
                            </tbody>
                        </table>
                    )}
                </div>
            </div>
        </>
    );
}

Index.layout = page => <FamilyLayout>{page}</FamilyLayout>;
