// resources/js/Layouts/AppLayoutShell.jsx
import React, { useState } from 'react';
import AppSidebar from '../Components/Layout/AppSidebar';
import AppMobileMenu from '../Components/Layout/AppMobileMenu';
import AppTopNavigation from '../Components/Layout/AppTopNavigation';
import NotificationsPanel from '../Components/Layout/NotificationsPanel';

export default function AppLayoutShell({ children, title = 'Dashboard', description = '', roleLabel = 'Workspace', navigation = [], user = {}, notifications = [] }) {
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    const [notificationsPanelOpen, setNotificationsPanelOpen] = useState(false);

    const unreadCount = notifications.filter((item) => item.unread).length;

    return (
        <div className="min-h-screen bg-surface-muted">
            <AppSidebar navigation={navigation} roleLabel={roleLabel} />

            <AppMobileMenu
                open={mobileMenuOpen}
                navigation={navigation}
                roleLabel={roleLabel}
                onClose={() => setMobileMenuOpen(false)}
            />

            <NotificationsPanel
                open={notificationsPanelOpen}
                notifications={notifications}
                onClose={() => setNotificationsPanelOpen(false)}
            />

            <div className="min-h-screen xl:pl-72">
                <AppTopNavigation
                    title={title}
                    description={description}
                    user={user}
                    unreadCount={unreadCount}
                    onToggleMobileMenu={() => setMobileMenuOpen(true)}
                    onToggleNotifications={() => setNotificationsPanelOpen(!notificationsPanelOpen)}
                />

                <main className="container-page section-gap">
                    {children}
                </main>
            </div>
        </div>
    );
}

// resources/js/Layouts/AppLayoutShell.vue
<script setup>
import { computed, ref } from 'vue';
import AppMobileMenu from '../Components/Layout/AppMobileMenu.vue';
import AppSidebar from '../Components/Layout/AppSidebar.vue';
import AppTopNavigation from '../Components/Layout/AppTopNavigation.vue';
import NotificationsPanel from '../Components/Layout/NotificationsPanel.vue';
import { useNotificationsPanel } from '../Composables/useNotificationsPanel';

const props = defineProps({
    title: {
        type: String,
        default: 'Dashboard',
    },
    description: {
        type: String,
        default: '',
    },
    roleLabel: {
        type: String,
        default: 'Workspace',
    },
    navigation: {
        type: Array,
        default: () => [],
    },
    user: {
        type: Object,
        default: () => ({}),
    },
    notifications: {
        type: Array,
        default: () => [],
    },
});

const mobileMenuOpen = ref(false);
const {
    isNotificationsPanelOpen,
    closeNotificationsPanel,
    toggleNotificationsPanel,
} = useNotificationsPanel();

const unreadCount = computed(() => props.notifications.filter((item) => item.unread).length);
</script>

<template>
    <div class="min-h-screen bg-surface-muted">
        <AppSidebar :navigation="navigation" :role-label="roleLabel" />

        <AppMobileMenu
            :open="mobileMenuOpen"
            :navigation="navigation"
            :role-label="roleLabel"
            @close="mobileMenuOpen = false"
        />

        <NotificationsPanel
            :open="isNotificationsPanelOpen"
            :notifications="notifications"
            @close="closeNotificationsPanel"
        />

        <div class="min-h-screen xl:pl-72">
            <AppTopNavigation
                :title="title"
                :description="description"
                :user="user"
                :unread-count="unreadCount"
                @toggle-mobile-menu="mobileMenuOpen = true"
                @toggle-notifications="toggleNotificationsPanel"
            />

            <main class="container-page section-gap">
                <slot />
            </main>
        </div>
    </div>
</template>
