// resources/js/Layouts/AuthLayout.jsx
import React from 'react';
import { usePage } from '@inertiajs/react';
import AppLayoutShell from './AppLayoutShell';

export default function AuthLayout({ children, title = 'Workspace', description = 'Manage your healthcare operations from one place.', roleLabel = 'Authenticated User', navigation = [], notifications = [] }) {
    const { props } = usePage();
    const user = props.auth?.user ?? {};

    return (
        <AppLayoutShell
            title={title}
            description={description}
            roleLabel={roleLabel}
            navigation={navigation}
            notifications={notifications}
            user={user}
        >
            {children}
        </AppLayoutShell>
    );
}

// resources/js/Layouts/AuthLayout.vue
<script setup>
import { computed } from 'vue';
import { usePage } from '@inertiajs/vue3';
import AppLayoutShell from './AppLayoutShell.vue';

const props = defineProps({
    title: {
        type: String,
        default: 'Workspace',
    },
    description: {
        type: String,
        default: 'Manage your healthcare operations from one place.',
    },
    roleLabel: {
        type: String,
        default: 'Authenticated User',
    },
    navigation: {
        type: Array,
        default: () => [],
    },
    notifications: {
        type: Array,
        default: () => [],
    },
});

const page = usePage();
const user = computed(() => page.props?.auth?.user ?? {});
</script>

<template>
    <AppLayoutShell
        :title="title"
        :description="description"
        :role-label="roleLabel"
        :navigation="navigation"
        :notifications="notifications"
        :user="user"
    >
        <slot />
    </AppLayoutShell>
</template>
