// resources/js/Pages/Auth/ForgotPassword.vue
<script setup>
import { Head, Link } from '@inertiajs/vue3';
import AuthAlert from '../../Components/Auth/AuthAlert.vue';
import AuthCard from '../../Components/Auth/AuthCard.vue';
import AuthInput from '../../Components/Auth/AuthInput.vue';
import { useApiForm } from '../../Composables/useApiForm';
import GuestLayout from '../../Layouts/GuestLayout.vue';

defineOptions({ layout: GuestLayout });

const { form, processing, message, messageTone, submit, setMessage, errorFor } = useApiForm({
    email: '',
});

const handleSubmit = async () => {
    try {
        const response = await submit({
            url: '/forgot-password',
            method: 'post',
        });

        setMessage(response.data?.message || 'Password reset link sent successfully.', 'success');
    } catch (error) {
        if (error.response?.status === 422) {
            setMessage('Please provide a valid email address.', 'danger');
        }
    }
};
</script>

<template>
    <Head title="Forgot Password" />

    <AuthCard
        title="Forgot your password?"
        subtitle="Enter your email and we’ll send you a secure reset link."
    >
        <AuthAlert
            v-if="message"
            :tone="messageTone"
            title="Password recovery"
            :message="message"
        />

        <form class="space-y-5" @submit.prevent="handleSubmit">
            <AuthInput
                id="forgot-password-email"
                v-model="form.email"
                label="Email address"
                type="email"
                placeholder="you@example.com"
                autocomplete="email"
                required
                :error="errorFor('email')"
            />

            <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <Link href="/login" class="btn-link">
                    Back to login
                </Link>

                <button type="submit" class="btn-primary" :disabled="processing">
                    {{ processing ? 'Sending link...' : 'Send reset link' }}
                </button>
            </div>
        </form>
    </AuthCard>
</template>

// resources/js/Pages/Auth/ForgotPassword.jsx
import React, { useState } from 'react';
import { Head, Link, useForm } from '@inertiajs/react';
import AuthCard from '../../Components/Auth/AuthCard';
import AuthInput from '../../Components/Auth/AuthInput';
import AuthAlert from '../../Components/Auth/AuthAlert';
import GuestLayout from '../../Layouts/GuestLayout';

export default function ForgotPassword() {
    const { data, setData, post, processing, errors } = useForm({
        email: '',
    });

    const [message, setMessage] = useState('');
    const [messageTone, setMessageTone] = useState('success');

    const handleSubmit = (e) => {
        e.preventDefault();
        setMessage('');

        post('/forgot-password', {
            onSuccess: (page) => {
                setMessage(page.props?.flash?.success || 'Password reset link sent successfully.');
                setMessageTone('success');
            },
            onError: (errs) => {
                setMessageTone('danger');
                if (errs.email) {
                    setMessage(errs.email);
                } else {
                    setMessage('Please provide a valid email address.');
                }
            },
        });
    };

    return (
        <GuestLayout
            title="Forgot your password?"
            subtitle="Enter your email and we'll send you a secure reset link."
        >
            <Head title="Forgot Password" />

            <AuthCard
                title="Forgot your password?"
                subtitle="Enter your email and we'll send you a secure reset link."
            >
                {message && (
                    <AuthAlert
                        tone={messageTone}
                        title="Password recovery"
                        message={message}
                    />
                )}

                <form className="space-y-5" onSubmit={handleSubmit}>
                    <AuthInput
                        id="forgot-password-email"
                        label="Email address"
                        type="email"
                        value={data.email}
                        placeholder="you@example.com"
                        autocomplete="email"
                        required
                        error={errors.email}
                        onChange={(val) => setData('email', val)}
                    />

                    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                        <Link href="/login" className="btn-link">
                            Back to login
                        </Link>

                        <button type="submit" className="btn-primary" disabled={processing}>
                            {processing ? 'Sending link...' : 'Send reset link'}
                        </button>
                    </div>
                </form>
            </AuthCard>
        </GuestLayout>
    );
}
