// resources/js/Pages/Auth/Register.jsx
import React, { useState } from 'react';
import { Head, Link, useForm } from '@inertiajs/react';
import AuthCard from '../../Components/Auth/AuthCard';
import AuthAlert from '../../Components/Auth/AuthAlert';
import AuthInput from '../../Components/Auth/AuthInput';
import AuthPasswordInput from '../../Components/Auth/AuthPasswordInput';
import AuthSelect from '../../Components/Auth/AuthSelect';
import GuestLayout from '../../Layouts/GuestLayout';

export default function Register() {
    const roleOptions = [
        { value: 'client', label: 'Client' },
        { value: 'family-member', label: 'Family Member' },
        { value: 'caregiver', label: 'Caregiver' },
    ];

    const { data, setData, post, processing, errors } = useForm({
        first_name: '',
        last_name: '',
        email: '',
        phone: '',
        password: '',
        password_confirmation: '',
        role: '',
        device_name: 'web',
        client: {
            date_of_birth: '',
            address_line_1: '',
            address_line_2: '',
            city: '',
            state: '',
            postal_code: '',
            country: 'Canada',
            emergency_contact_name: '',
            emergency_contact_phone: '',
            care_notes: '',
            mobility_notes: '',
            medical_notes: '',
        },
        family_member: {
            client_id: '',
            relationship_type: '',
            can_view_bookings: true,
            can_view_reports: true,
            can_view_invoices: true,
            can_receive_notifications: true,
        },
        caregiver: {
            address_line_1: '',
            address_line_2: '',
            city: '',
            state: '',
            postal_code: '',
            country: 'Canada',
            certifications: '',
            emergency_contact_name: '',
            emergency_contact_phone: '',
            bio: '',
        },
    });

    const [message, setMessage] = useState('');

    const handleSubmit = (e) => {
        e.preventDefault();
        setMessage('');

        const payload = structuredClone(data);
        if (payload.caregiver?.certifications && typeof payload.caregiver.certifications === 'string') {
            payload.caregiver.certifications = payload.caregiver.certifications
                .split(',')
                .map((item) => item.trim())
                .filter(Boolean);
        } else {
            payload.caregiver.certifications = [];
        }

        if (payload.family_member?.client_id === '') {
            payload.family_member.client_id = null;
        }

        // We can just use the standard inertia post, which handles tokens if configured.
        post('/register', {
            onSuccess: (page) => {
                const token = page.props?.token;
                if (token) {
                    localStorage.setItem('auth_token', token);
                    window.axios.defaults.headers.common['Authorization'] = `Bearer ${token}`;
                }
                localStorage.setItem('auth_flash_success', page.props?.flash?.success || 'Registration successful.');
            },
            onError: (errs) => {
                setMessage('Please correct the highlighted fields and try again.');
            }
        });
    };

    return (
        <GuestLayout
            title="Create your account"
            subtitle="Join Royal Grace to access coordinated care, family visibility, and secure communication."
        >
            <Head title="Register" />

            <AuthCard
                title="Create your account"
                subtitle="Join Royal Grace to access coordinated care, family visibility, and secure communication."
            >
                {message && (
                    <AuthAlert
                        tone="danger"
                        title="Registration update"
                        message={message}
                    />
                )}

                <form className="space-y-6" onSubmit={handleSubmit}>
                    <div className="grid gap-5 md:grid-cols-2">
                        <AuthInput
                            id="register-first-name"
                            value={data.first_name}
                            onChange={val => setData('first_name', val)}
                            label="First name"
                            placeholder="John"
                            autocomplete="given-name"
                            required
                            error={errors.first_name}
                        />

                        <AuthInput
                            id="register-last-name"
                            value={data.last_name}
                            onChange={val => setData('last_name', val)}
                            label="Last name"
                            placeholder="Doe"
                            autocomplete="family-name"
                            required
                            error={errors.last_name}
                        />
                    </div>

                    <div className="grid gap-5 md:grid-cols-2">
                        <AuthInput
                            id="register-email"
                            value={data.email}
                            onChange={val => setData('email', val)}
                            label="Email address"
                            type="email"
                            placeholder="you@example.com"
                            autocomplete="email"
                            required
                            error={errors.email}
                        />

                        <AuthInput
                            id="register-phone"
                            value={data.phone}
                            onChange={val => setData('phone', val)}
                            label="Phone number"
                            type="tel"
                            placeholder="+1..."
                            autocomplete="tel"
                            error={errors.phone}
                        />
                    </div>

                    <AuthSelect
                        id="register-role"
                        value={data.role}
                        onChange={val => setData('role', val)}
                        label="Account type"
                        options={roleOptions}
                        required
                        error={errors.role}
                    />

                    <div className="grid gap-5 md:grid-cols-2">
                        <AuthPasswordInput
                            id="register-password"
                            value={data.password}
                            onChange={val => setData('password', val)}
                            label="Password"
                            placeholder="Create a strong password"
                            autocomplete="new-password"
                            required
                            help="Minimum 8 characters."
                            error={errors.password}
                        />

                        <AuthPasswordInput
                            id="register-password-confirmation"
                            value={data.password_confirmation}
                            onChange={val => setData('password_confirmation', val)}
                            label="Confirm password"
                            placeholder="Repeat your password"
                            autocomplete="new-password"
                            required
                            error={errors.password_confirmation}
                        />
                    </div>

                    {data.role === 'client' && (
                        <div className="pt-4 border-t border-border space-y-5">
                            <div>
                                <h3 className="text-lg font-semibold text-text">Client profile</h3>
                                <p className="text-sm text-text-muted">Tell us about the care recipient so bookings and care coordination can start smoothly.</p>
                            </div>

                            <div className="grid gap-5 md:grid-cols-2">
                                <AuthInput
                                    id="client-date-of-birth"
                                    value={data.client.date_of_birth}
                                    onChange={val => setData('client', { ...data.client, date_of_birth: val })}
                                    label="Date of birth"
                                    type="date"
                                    error={errors['client.date_of_birth']}
                                />

                                <AuthInput
                                    id="client-emergency-contact-name"
                                    value={data.client.emergency_contact_name}
                                    onChange={val => setData('client', { ...data.client, emergency_contact_name: val })}
                                    label="Emergency contact name"
                                    placeholder="Primary emergency contact"
                                    error={errors['client.emergency_contact_name']}
                                />
                            </div>

                            <div className="grid gap-5 md:grid-cols-2">
                                <AuthInput
                                    id="client-address-line-1"
                                    value={data.client.address_line_1}
                                    onChange={val => setData('client', { ...data.client, address_line_1: val })}
                                    label="Address line 1"
                                    required
                                    error={errors['client.address_line_1']}
                                />

                                <AuthInput
                                    id="client-address-line-2"
                                    value={data.client.address_line_2}
                                    onChange={val => setData('client', { ...data.client, address_line_2: val })}
                                    label="Address line 2"
                                    error={errors['client.address_line_2']}
                                />
                            </div>

                            <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">
                                <AuthInput id="client-city" value={data.client.city} onChange={val => setData('client', { ...data.client, city: val })} label="City" required error={errors['client.city']} />
                                <AuthInput id="client-state" value={data.client.state} onChange={val => setData('client', { ...data.client, state: val })} label="Province/State" required error={errors['client.state']} />
                                <AuthInput id="client-postal-code" value={data.client.postal_code} onChange={val => setData('client', { ...data.client, postal_code: val })} label="Postal code" required error={errors['client.postal_code']} />
                                <AuthInput id="client-country" value={data.client.country} onChange={val => setData('client', { ...data.client, country: val })} label="Country" required error={errors['client.country']} />
                            </div>

                            <div className="grid gap-5 md:grid-cols-2">
                                <AuthInput
                                    id="client-emergency-contact-phone"
                                    value={data.client.emergency_contact_phone}
                                    onChange={val => setData('client', { ...data.client, emergency_contact_phone: val })}
                                    label="Emergency contact phone"
                                    error={errors['client.emergency_contact_phone']}
                                />

                                <AuthInput
                                    id="client-care-notes"
                                    value={data.client.care_notes}
                                    onChange={val => setData('client', { ...data.client, care_notes: val })}
                                    label="Care notes"
                                    placeholder="Brief care requirements"
                                    error={errors['client.care_notes']}
                                />
                            </div>

                            <div className="grid gap-5 md:grid-cols-2">
                                <AuthInput
                                    id="client-mobility-notes"
                                    value={data.client.mobility_notes}
                                    onChange={val => setData('client', { ...data.client, mobility_notes: val })}
                                    label="Mobility notes"
                                    error={errors['client.mobility_notes']}
                                />

                                <AuthInput
                                    id="client-medical-notes"
                                    value={data.client.medical_notes}
                                    onChange={val => setData('client', { ...data.client, medical_notes: val })}
                                    label="Medical notes"
                                    error={errors['client.medical_notes']}
                                />
                            </div>
                        </div>
                    )}

                    {data.role === 'family-member' && (
                        <div className="pt-4 border-t border-border space-y-5">
                            <div>
                                <h3 className="text-lg font-semibold text-text">Family access details</h3>
                                <p className="text-sm text-text-muted">Link this account to an existing client record and define the visibility level.</p>
                            </div>

                            <div className="grid gap-5 md:grid-cols-2">
                                <AuthInput
                                    id="family-client-id"
                                    value={data.family_member.client_id}
                                    onChange={val => setData('family_member', { ...data.family_member, client_id: val })}
                                    label="Client ID"
                                    type="number"
                                    required
                                    help="Use the client ID provided by an admin."
                                    error={errors['family_member.client_id']}
                                />

                                <AuthInput
                                    id="family-relationship-type"
                                    value={data.family_member.relationship_type}
                                    onChange={val => setData('family_member', { ...data.family_member, relationship_type: val })}
                                    label="Relationship"
                                    placeholder="Son, Daughter, Spouse..."
                                    required
                                    error={errors['family_member.relationship_type']}
                                />
                            </div>

                            <div className="grid gap-4 md:grid-cols-2">
                                <label className="flex items-center gap-2">
                                    <input type="checkbox" checked={data.family_member.can_view_bookings} onChange={e => setData('family_member', { ...data.family_member, can_view_bookings: e.target.checked })} />
                                    <span className="text-sm text-text">Can view bookings</span>
                                </label>
                                <label className="flex items-center gap-2">
                                    <input type="checkbox" checked={data.family_member.can_view_reports} onChange={e => setData('family_member', { ...data.family_member, can_view_reports: e.target.checked })} />
                                    <span className="text-sm text-text">Can view reports</span>
                                </label>
                                <label className="flex items-center gap-2">
                                    <input type="checkbox" checked={data.family_member.can_view_invoices} onChange={e => setData('family_member', { ...data.family_member, can_view_invoices: e.target.checked })} />
                                    <span className="text-sm text-text">Can view invoices</span>
                                </label>
                                <label className="flex items-center gap-2">
                                    <input type="checkbox" checked={data.family_member.can_receive_notifications} onChange={e => setData('family_member', { ...data.family_member, can_receive_notifications: e.target.checked })} />
                                    <span className="text-sm text-text">Can receive notifications</span>
                                </label>
                            </div>
                        </div>
                    )}

                    {data.role === 'caregiver' && (
                        <div className="pt-4 border-t border-border space-y-5">
                            <div>
                                <h3 className="text-lg font-semibold text-text">Caregiver profile</h3>
                                <p className="text-sm text-text-muted">Add profile and compliance details needed for caregiver onboarding.</p>
                            </div>

                            <div className="grid gap-5 md:grid-cols-2">
                                <AuthInput
                                    id="caregiver-address-line-1"
                                    value={data.caregiver.address_line_1}
                                    onChange={val => setData('caregiver', { ...data.caregiver, address_line_1: val })}
                                    label="Address line 1"
                                    required
                                    error={errors['caregiver.address_line_1']}
                                />

                                <AuthInput
                                    id="caregiver-address-line-2"
                                    value={data.caregiver.address_line_2}
                                    onChange={val => setData('caregiver', { ...data.caregiver, address_line_2: val })}
                                    label="Address line 2"
                                    error={errors['caregiver.address_line_2']}
                                />
                            </div>

                            <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">
                                <AuthInput id="caregiver-city" value={data.caregiver.city} onChange={val => setData('caregiver', { ...data.caregiver, city: val })} label="City" required error={errors['caregiver.city']} />
                                <AuthInput id="caregiver-state" value={data.caregiver.state} onChange={val => setData('caregiver', { ...data.caregiver, state: val })} label="Province/State" required error={errors['caregiver.state']} />
                                <AuthInput id="caregiver-postal-code" value={data.caregiver.postal_code} onChange={val => setData('caregiver', { ...data.caregiver, postal_code: val })} label="Postal code" required error={errors['caregiver.postal_code']} />
                                <AuthInput id="caregiver-country" value={data.caregiver.country} onChange={val => setData('caregiver', { ...data.caregiver, country: val })} label="Country" required error={errors['caregiver.country']} />
                            </div>

                            <div className="grid gap-5 md:grid-cols-2">
                                <AuthInput
                                    id="caregiver-emergency-contact-name"
                                    value={data.caregiver.emergency_contact_name}
                                    onChange={val => setData('caregiver', { ...data.caregiver, emergency_contact_name: val })}
                                    label="Emergency contact name"
                                    required
                                    error={errors['caregiver.emergency_contact_name']}
                                />

                                <AuthInput
                                    id="caregiver-emergency-contact-phone"
                                    value={data.caregiver.emergency_contact_phone}
                                    onChange={val => setData('caregiver', { ...data.caregiver, emergency_contact_phone: val })}
                                    label="Emergency contact phone"
                                    required
                                    error={errors['caregiver.emergency_contact_phone']}
                                />
                            </div>

                            <div className="grid gap-5 md:grid-cols-2">
                                <AuthInput
                                    id="caregiver-certifications"
                                    value={data.caregiver.certifications}
                                    onChange={val => setData('caregiver', { ...data.caregiver, certifications: val })}
                                    label="Certifications"
                                    placeholder="CPR, Geriatric Care, First Aid"
                                    help="Separate multiple certifications with commas."
                                    error={errors['caregiver.certifications']}
                                />

                                <AuthInput
                                    id="caregiver-bio"
                                    value={data.caregiver.bio}
                                    onChange={val => setData('caregiver', { ...data.caregiver, bio: val })}
                                    label="Short bio"
                                    placeholder="Experience, specialties, and care approach"
                                    error={errors['caregiver.bio']}
                                />
                            </div>
                        </div>
                    )}

                    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between border-t border-border pt-4">
                        <Link href="/login" className="btn-link">
                            Already have an account?
                        </Link>

                        <button type="submit" className="btn-primary" disabled={processing}>
                            {processing ? 'Creating account...' : 'Create account'}
                        </button>
                    </div>
                </form>
            </AuthCard>
        </GuestLayout>
    );
}

// resources/js/Pages/Auth/Register.vue
<script setup>
import { Head, Link, router } from '@inertiajs/vue3';
import axios from 'axios';
import AuthAlert from '../../Components/Auth/AuthAlert.vue';
import AuthCard from '../../Components/Auth/AuthCard.vue';
import AuthCheckbox from '../../Components/Auth/AuthCheckbox.vue';
import AuthInput from '../../Components/Auth/AuthInput.vue';
import AuthPasswordInput from '../../Components/Auth/AuthPasswordInput.vue';
import AuthSelect from '../../Components/Auth/AuthSelect.vue';
import { useApiForm } from '../../Composables/useApiForm';
import GuestLayout from '../../Layouts/GuestLayout.vue';

defineOptions({ layout: GuestLayout });

const roleOptions = [
    { value: 'client', label: 'Client' },
    { value: 'family-member', label: 'Family Member' },
    { value: 'caregiver', label: 'Caregiver' },
];

const { form, processing, message, messageTone, submit, setMessage, errorFor } = useApiForm({
    first_name: '',
    last_name: '',
    email: '',
    phone: '',
    password: '',
    password_confirmation: '',
    role: '',
    device_name: 'web',
    client: {
        date_of_birth: '',
        address_line_1: '',
        address_line_2: '',
        city: '',
        state: '',
        postal_code: '',
        country: 'Nigeria',
        emergency_contact_name: '',
        emergency_contact_phone: '',
        care_notes: '',
        mobility_notes: '',
        medical_notes: '',
    },
    family_member: {
        client_id: '',
        relationship_type: '',
        can_view_bookings: true,
        can_view_reports: true,
        can_view_invoices: true,
        can_receive_notifications: true,
    },
    caregiver: {
        address_line_1: '',
        address_line_2: '',
        city: '',
        state: '',
        postal_code: '',
        country: 'Nigeria',
        certifications: '',
        emergency_contact_name: '',
        emergency_contact_phone: '',
        bio: '',
    },
});

const handleSubmit = async () => {
    const payload = structuredClone(form);

    if (payload.caregiver?.certifications) {
        payload.caregiver.certifications = payload.caregiver.certifications
            .split(',')
            .map((item) => item.trim())
            .filter(Boolean);
    } else {
        payload.caregiver.certifications = [];
    }

    if (payload.family_member?.client_id === '') {
        payload.family_member.client_id = null;
    }

    try {
        const response = await submit({
            url: '/register',
            method: 'post',
            data: payload,
        });

        const { token, message: successMessage } = response.data;

        if (token) {
            localStorage.setItem('auth_token', token);
            axios.defaults.headers.common.Authorization = `Bearer ${token}`;
        }

        localStorage.setItem('auth_flash_success', successMessage || 'Registration successful.');
        router.visit('/email/verify');
    } catch (error) {
        if (error.response?.status === 422) {
            setMessage('Please correct the highlighted fields and try again.', 'danger');
        }
    }
};
</script>

<template>
    <Head title="Register" />

    <AuthCard
        title="Create your account"
        subtitle="Join Royal Grace to access coordinated care, family visibility, and secure communication."
    >
        <AuthAlert
            v-if="message"
            :tone="messageTone"
            title="Registration update"
            :message="message"
        />

        <form class="space-y-6" @submit.prevent="handleSubmit">
            <div class="grid gap-5 md:grid-cols-2">
                <AuthInput
                    id="register-first-name"
                    v-model="form.first_name"
                    label="First name"
                    placeholder="Olayinka"
                    autocomplete="given-name"
                    required
                    :error="errorFor('first_name')"
                />

                <AuthInput
                    id="register-last-name"
                    v-model="form.last_name"
                    label="Last name"
                    placeholder="Adewale"
                    autocomplete="family-name"
                    required
                    :error="errorFor('last_name')"
                />
            </div>

            <div class="grid gap-5 md:grid-cols-2">
                <AuthInput
                    id="register-email"
                    v-model="form.email"
                    label="Email address"
                    type="email"
                    placeholder="you@example.com"
                    autocomplete="email"
                    required
                    :error="errorFor('email')"
                />

                <AuthInput
                    id="register-phone"
                    v-model="form.phone"
                    label="Phone number"
                    type="tel"
                    placeholder="+234..."
                    autocomplete="tel"
                    :error="errorFor('phone')"
                />
            </div>

            <div class="grid gap-5 md:grid-cols-2">
                <AuthSelect
                    id="register-role"
                    v-model="form.role"
                    label="Account type"
                    :options="roleOptions"
                    required
                    :error="errorFor('role')"
                />

                <AuthInput
                    id="register-device-name"
                    v-model="form.device_name"
                    label="Device name"
                    placeholder="Web browser"
                    :error="errorFor('device_name')"
                />
            </div>

            <div class="grid gap-5 md:grid-cols-2">
                <AuthPasswordInput
                    id="register-password"
                    v-model="form.password"
                    label="Password"
                    placeholder="Create a strong password"
                    autocomplete="new-password"
                    required
                    help="Minimum 8 characters."
                    :error="errorFor('password')"
                />

                <AuthPasswordInput
                    id="register-password-confirmation"
                    v-model="form.password_confirmation"
                    label="Confirm password"
                    placeholder="Repeat your password"
                    autocomplete="new-password"
                    required
                    :error="errorFor('password_confirmation')"
                />
            </div>

            <section v-if="form.role === 'client'" class="form-section">
                <div>
                    <h3 class="text-lg font-semibold text-text">Client profile</h3>
                    <p class="text-sm text-text-muted">Tell us about the care recipient so bookings and care coordination can start smoothly.</p>
                </div>

                <div class="grid gap-5 md:grid-cols-2">
                    <AuthInput
                        id="client-date-of-birth"
                        v-model="form.client.date_of_birth"
                        label="Date of birth"
                        type="date"
                        :error="errorFor('client.date_of_birth')"
                    />

                    <AuthInput
                        id="client-emergency-contact-name"
                        v-model="form.client.emergency_contact_name"
                        label="Emergency contact name"
                        placeholder="Primary emergency contact"
                        :error="errorFor('client.emergency_contact_name')"
                    />
                </div>

                <div class="grid gap-5 md:grid-cols-2">
                    <AuthInput
                        id="client-address-line-1"
                        v-model="form.client.address_line_1"
                        label="Address line 1"
                        required
                        :error="errorFor('client.address_line_1')"
                    />

                    <AuthInput
                        id="client-address-line-2"
                        v-model="form.client.address_line_2"
                        label="Address line 2"
                        :error="errorFor('client.address_line_2')"
                    />
                </div>

                <div class="grid gap-5 md:grid-cols-2 lg:grid-cols-4">
                    <AuthInput id="client-city" v-model="form.client.city" label="City" required :error="errorFor('client.city')" />
                    <AuthInput id="client-state" v-model="form.client.state" label="State" required :error="errorFor('client.state')" />
                    <AuthInput id="client-postal-code" v-model="form.client.postal_code" label="Postal code" required :error="errorFor('client.postal_code')" />
                    <AuthInput id="client-country" v-model="form.client.country" label="Country" required :error="errorFor('client.country')" />
                </div>

                <div class="grid gap-5 md:grid-cols-2">
                    <AuthInput
                        id="client-emergency-contact-phone"
                        v-model="form.client.emergency_contact_phone"
                        label="Emergency contact phone"
                        :error="errorFor('client.emergency_contact_phone')"
                    />

                    <AuthInput
                        id="client-care-notes"
                        v-model="form.client.care_notes"
                        label="Care notes"
                        placeholder="Brief care requirements"
                        :error="errorFor('client.care_notes')"
                    />
                </div>

                <div class="grid gap-5 md:grid-cols-2">
                    <AuthInput
                        id="client-mobility-notes"
                        v-model="form.client.mobility_notes"
                        label="Mobility notes"
                        :error="errorFor('client.mobility_notes')"
                    />

                    <AuthInput
                        id="client-medical-notes"
                        v-model="form.client.medical_notes"
                        label="Medical notes"
                        :error="errorFor('client.medical_notes')"
                    />
                </div>
            </section>

            <section v-if="form.role === 'family-member'" class="form-section">
                <div>
                    <h3 class="text-lg font-semibold text-text">Family access details</h3>
                    <p class="text-sm text-text-muted">Link this account to an existing client record and define the visibility level.</p>
                </div>

                <div class="grid gap-5 md:grid-cols-2">
                    <AuthInput
                        id="family-client-id"
                        v-model="form.family_member.client_id"
                        label="Client ID"
                        type="number"
                        required
                        help="Use the client ID provided by an admin."
                        :error="errorFor('family_member.client_id')"
                    />

                    <AuthInput
                        id="family-relationship-type"
                        v-model="form.family_member.relationship_type"
                        label="Relationship"
                        placeholder="Son, Daughter, Spouse..."
                        required
                        :error="errorFor('family_member.relationship_type')"
                    />
                </div>

                <div class="grid gap-4 md:grid-cols-2">
                    <AuthCheckbox
                        id="family-can-view-bookings"
                        v-model="form.family_member.can_view_bookings"
                        label="Can view bookings"
                    />
                    <AuthCheckbox
                        id="family-can-view-reports"
                        v-model="form.family_member.can_view_reports"
                        label="Can view reports"
                    />
                    <AuthCheckbox
                        id="family-can-view-invoices"
                        v-model="form.family_member.can_view_invoices"
                        label="Can view invoices"
                    />
                    <AuthCheckbox
                        id="family-can-receive-notifications"
                        v-model="form.family_member.can_receive_notifications"
                        label="Can receive notifications"
                    />
                </div>
            </section>

            <section v-if="form.role === 'caregiver'" class="form-section">
                <div>
                    <h3 class="text-lg font-semibold text-text">Caregiver profile</h3>
                    <p class="text-sm text-text-muted">Add profile and compliance details needed for caregiver onboarding.</p>
                </div>

                <div class="grid gap-5 md:grid-cols-2">
                    <AuthInput
                        id="caregiver-address-line-1"
                        v-model="form.caregiver.address_line_1"
                        label="Address line 1"
                        required
                        :error="errorFor('caregiver.address_line_1')"
                    />

                    <AuthInput
                        id="caregiver-address-line-2"
                        v-model="form.caregiver.address_line_2"
                        label="Address line 2"
                        :error="errorFor('caregiver.address_line_2')"
                    />
                </div>

                <div class="grid gap-5 md:grid-cols-2 lg:grid-cols-4">
                    <AuthInput id="caregiver-city" v-model="form.caregiver.city" label="City" required :error="errorFor('caregiver.city')" />
                    <AuthInput id="caregiver-state" v-model="form.caregiver.state" label="State" required :error="errorFor('caregiver.state')" />
                    <AuthInput id="caregiver-postal-code" v-model="form.caregiver.postal_code" label="Postal code" required :error="errorFor('caregiver.postal_code')" />
                    <AuthInput id="caregiver-country" v-model="form.caregiver.country" label="Country" required :error="errorFor('caregiver.country')" />
                </div>

                <div class="grid gap-5 md:grid-cols-2">
                    <AuthInput
                        id="caregiver-emergency-contact-name"
                        v-model="form.caregiver.emergency_contact_name"
                        label="Emergency contact name"
                        required
                        :error="errorFor('caregiver.emergency_contact_name')"
                    />

                    <AuthInput
                        id="caregiver-emergency-contact-phone"
                        v-model="form.caregiver.emergency_contact_phone"
                        label="Emergency contact phone"
                        required
                        :error="errorFor('caregiver.emergency_contact_phone')"
                    />
                </div>

                <div class="grid gap-5 md:grid-cols-2">
                    <AuthInput
                        id="caregiver-certifications"
                        v-model="form.caregiver.certifications"
                        label="Certifications"
                        placeholder="CPR, Geriatric Care, First Aid"
                        help="Separate multiple certifications with commas."
                        :error="errorFor('caregiver.certifications')"
                    />

                    <AuthInput
                        id="caregiver-bio"
                        v-model="form.caregiver.bio"
                        label="Short bio"
                        placeholder="Experience, specialties, and care approach"
                        :error="errorFor('caregiver.bio')"
                    />
                </div>
            </section>

            <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                <Link href="/login" class="btn-link">
                    Already have an account?
                </Link>

                <button type="submit" class="btn-primary" :disabled="processing">
                    {{ processing ? 'Creating account...' : 'Create account' }}
                </button>
            </div>
        </form>
    </AuthCard>
</template>
